const RouteName = {
    // auth
    SPLASH_SCREEN: "SPLASH_SCREEN",
    WELCOME_SCREEN: "WELCOME_SCREEN",
    LOGIN_SCREEN: "LOGIN_SCREEN",
    REGISTER_SCREEN: "REGISTER_SCREEN",
    FORGOT_PASSWORD_SCREEN: "FORGOT_PASSWORD_SCREEN",

    // routes
    BOTTOM_TAB: "BOTTOM_TAB",
    
    // main
    HOME_SCREEN: "HOME_SCREEN",
    DETECTION_SCREEN: "DETECTION_SCREEN",
    CONVERTER_SCREEN: "CONVERTER_SCREEN",
    SETTING_SCREEN: "SETTING_SCREEN",
    RESULT_SCREEN: "RESULT_SCREEN",
};

export default RouteName;